// GENERATED by scripts/seed-model-prices.mjs. Do not edit by hand.
//
// Written from model_cost_and_speed, which is what vendors actually charged.
// Re-run the script to refresh it as more models accumulate history; edits
// here are lost the next time it runs. Published prices for models with no
// history go in ./seed-prices.manual.ts instead.
//
// Images are credits per generation, video is credits per second, both in the
// vendor's own credit. A resolution key is a figure measured at that
// resolution; `flat` is the blend across every run of that model.
//
// kie image: 9, kie video: 6, poyo image: 18, poyo video: 5
// cells taken from staging: 69, from production: 1
import type { SeedTable } from "./seed-types";

export const GENERATED_SEED: SeedTable = {
  "kie": {
    "image": {
      "bytedance/seedream-v4-text-to-image": {
        "flat": 5
      },
      "flux-2/flex-text-to-image": {
        "flat": 14
      },
      "flux-2/pro-text-to-image": {
        "flat": 5
      },
      "google/imagen4-ultra": {
        "flat": 12
      },
      "gpt-image-2-text-to-image": {
        "flat": 6
      },
      "grok-imagine/text-to-image": {
        "flat": 4
      },
      "nano-banana-2": {
        "flat": 8
      },
      "nano-banana-pro": {
        "flat": 18
      },
      "z-image": {
        "flat": 0.8
      }
    },
    "video": {
      "bytedance/seedance-1.5-pro": {
        "flat": 3.5
      },
      "bytedance/seedance-2": {
        "flat": 41
      },
      "bytedance/seedance-2-fast": {
        "flat": 33
      },
      "grok-imagine/image-to-video": {
        "flat": 1.6
      },
      "kling-3.0/video": {
        "byResolution": {
          "pro": 18,
          "std": 14
        },
        "flat": 14
      },
      "wan/2-7-image-to-video": {
        "flat": 16,
        "byResolution": {
          "720p": 16
        }
      }
    }
  },
  "poyo": {
    "image": {
      "flux-dev": {
        "flat": 4
      },
      "gpt-4o-image": {
        "flat": 4
      },
      "gpt-image-1.5": {
        "flat": 2
      },
      "gpt-image-2": {
        "flat": 2,
        "byResolution": {
          "1K": 2,
          "2K": 4,
          "4K": 4
        }
      },
      "grok-imagine": {
        "flat": 30
      },
      "grok-imagine-image": {
        "flat": 6
      },
      "grok-imagine-image-2.0": {
        "flat": 12,
        "byResolution": {
          "1K": 12,
          "2K": 16
        }
      },
      "kling-o3-image": {
        "flat": 3.5,
        "byResolution": {
          "1K": 3.5,
          "2K": 3.5,
          "4K": 7
        }
      },
      "nano-banana": {
        "flat": 5
      },
      "nano-banana-2": {
        "byResolution": {
          "1K": 8,
          "2K": 8,
          "4K": 14
        },
        "flat": 8
      },
      "nano-banana-2-lite": {
        "flat": 5
      },
      "nano-banana-pro": {
        "flat": 18,
        "byResolution": {
          "1K": 18,
          "2K": 18,
          "4K": 35
        }
      },
      "seedream-4": {
        "flat": 5,
        "byResolution": {
          "1K": 5,
          "2K": 5,
          "4K": 5
        }
      },
      "seedream-4.5": {
        "flat": 5,
        "byResolution": {
          "2K": 5,
          "4K": 5
        }
      },
      "seedream-5.0-lite": {
        "flat": 5,
        "byResolution": {
          "2K": 5,
          "3K": 5
        }
      },
      "seedream-5.0-pro": {
        "flat": 15,
        "byResolution": {
          "1K": 15,
          "2K": 15
        }
      },
      "wan-2.7-image": {
        "flat": 4.2
      },
      "z-image": {
        "flat": 2
      }
    },
    "video": {
      "bytedance/seedance-1.5-pro": {
        "flat": 2.25,
        "byResolution": {
          "480p": 2.25
        }
      },
      "bytedance/seedance-2": {
        "byResolution": {
          "480p": 20
        },
        "flat": 20
      },
      "grok-imagine/image-to-video": {
        "flat": 3.75,
        "byResolution": {
          "480p": 5,
          "720p": 3.75
        }
      },
      "runway": {
        "flat": 15,
        "byResolution": {
          "720p": 15
        }
      },
      "veo3_fast": {
        "byResolution": {
          "720p": 9
        },
        "flat": 9
      }
    }
  }
};
