-- Custom sound effects and elements, uploaded by the customer.
--
-- The built-in libraries are 24 sounds and 18 elements, all generated by
-- scripts in the worker repo, and every id is a filename under assets/. That is
-- why the three columns below are whitelists: an id that is not a file is a
-- render that skips the cue with nothing to show for it.
--
-- A customer's own file cannot be in that list, so the whitelists gain one more
-- shape: 'custom:<uuid>', resolved through user_assets. Still not free text —
-- an id that does not parse as one of ours or as a uuid is still rejected by
-- the database, which is the property worth keeping.

CREATE TABLE IF NOT EXISTS user_assets (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  -- 'sound' plays on the timeline, 'element' is drawn on the frame. They are
  -- one table because they are one thing to the customer, one upload flow, and
  -- one storage allowance.
  kind         TEXT NOT NULL CHECK (kind IN ('sound', 'element')),
  -- What the customer called it. Shown in the picker beside the built-ins.
  name         TEXT NOT NULL CHECK (length(trim(name)) BETWEEN 1 AND 60),
  -- The R2 object key, not a URL. The public URL is derived from it server
  -- side, so a client cannot register an asset that points anywhere else and
  -- have the worker fetch it.
  storage_key  TEXT NOT NULL,
  mime         TEXT NOT NULL,
  bytes        BIGINT NOT NULL CHECK (bytes > 0),
  -- Sounds only. Lets the picker show a length and the trim UI size a block
  -- without decoding the file first. Null until measured.
  duration_sec NUMERIC,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS user_assets_user_kind_idx ON user_assets (user_id, kind, created_at DESC);
-- One row per object. A retried registration after a successful upload updates
-- rather than duplicating, and a duplicate key cannot bill storage twice.
CREATE UNIQUE INDEX IF NOT EXISTS user_assets_storage_key_idx ON user_assets (storage_key);

ALTER TABLE user_assets ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS user_assets_own ON user_assets;
CREATE POLICY user_assets_own ON user_assets
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- The shared shape. Kept as one expression so the three constraints below
-- cannot drift from each other.
CREATE OR REPLACE FUNCTION is_custom_asset_ref(v TEXT) RETURNS BOOLEAN
  LANGUAGE sql IMMUTABLE AS $$
    SELECT v ~ '^custom:[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
  $$;

ALTER TABLE project_sounds DROP CONSTRAINT IF EXISTS project_sounds_kind_check;
ALTER TABLE project_sounds ADD CONSTRAINT project_sounds_kind_check CHECK (
  is_custom_asset_ref(sound) OR sound IN (
    'whoosh', 'reverse-whoosh', 'swish', 'sweep', 'page',
    'click', 'tick', 'pop', 'beep', 'glitch', 'shutter',
    'zoom-in', 'zoom-out', 'riser',
    'impact', 'boom', 'thud', 'heartbeat',
    'chime', 'ding', 'sparkle',
    'bell', 'notification', 'alert'
  )
);

ALTER TABLE project_beats DROP CONSTRAINT IF EXISTS project_beats_sound_effect_check;
ALTER TABLE project_beats ADD CONSTRAINT project_beats_sound_effect_check CHECK (
  sound_effect IS NULL OR is_custom_asset_ref(sound_effect) OR sound_effect IN (
    'whoosh', 'reverse-whoosh', 'swish', 'sweep', 'page',
    'click', 'tick', 'pop', 'beep', 'glitch', 'shutter',
    'zoom-in', 'zoom-out', 'riser',
    'impact', 'boom', 'thud', 'heartbeat',
    'chime', 'ding', 'sparkle',
    'bell', 'notification', 'alert'
  )
);

ALTER TABLE project_elements DROP CONSTRAINT IF EXISTS project_elements_kind_check;
ALTER TABLE project_elements ADD CONSTRAINT project_elements_kind_check CHECK (
  is_custom_asset_ref(element) OR element IN (
    'subscribe', 'subscribed', 'like', 'share', 'follow', 'comment', 'new', 'live',
    'bell', 'bell-ring',
    'youtube', 'instagram', 'tiktok', 'facebook', 'x', 'whatsapp',
    'heart', 'thumbs-up'
  )
);
